/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CandyScoreboard: typeof import('./components/intel/CandyScoreboard.vue')['default']
    DashChart: typeof import('./components/DashChart.vue')['default']
    HealthPulse: typeof import('./components/HealthPulse.vue')['default']
    HealthTag: typeof import('./components/HealthTag.vue')['default']
    IntelPlanModal: typeof import('./components/intel/IntelPlanModal.vue')['default']
    KeyFormModal: typeof import('./components/upstreams/KeyFormModal.vue')['default']
    ModelListModal: typeof import('./components/ModelListModal.vue')['default']
    NoticeInbox: typeof import('./components/NoticeInbox.vue')['default']
    PelicanGallery: typeof import('./components/intel/PelicanGallery.vue')['default']
    ProbeModal: typeof import('./components/ProbeModal.vue')['default']
    ProviderDetail: typeof import('./components/upstreams/ProviderDetail.vue')['default']
    ProviderRail: typeof import('./components/upstreams/ProviderRail.vue')['default']
    RouteGroupKeyPicker: typeof import('./components/RouteGroupKeyPicker.vue')['default']
    RouteGroupTags: typeof import('./components/RouteGroupTags.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
    SystemUpdateModal: typeof import('./components/SystemUpdateModal.vue')['default']
    UiAlert: typeof import('@/components/ui')['UiAlert']
    UiBadge: typeof import('@/components/ui')['UiBadge']
    UiButton: typeof import('@/components/ui')['UiButton']
    UiCard: typeof import('@/components/ui')['UiCard']
    UiCheckbox: typeof import('@/components/ui')['UiCheckbox']
    UiCheckboxGroup: typeof import('@/components/ui')['UiCheckboxGroup']
    UiDataTable: typeof import('@/components/ui')['UiDataTable']
    UiDatePicker: typeof import('@/components/ui')['UiDatePicker']
    UiDrawer: typeof import('@/components/ui')['UiDrawer']
    UiDrawerContent: typeof import('@/components/ui')['UiDrawerContent']
    UiDynamicTags: typeof import('@/components/ui')['UiDynamicTags']
    UiEmpty: typeof import('@/components/ui')['UiEmpty']
    UiForm: typeof import('@/components/ui')['UiForm']
    UiFormItem: typeof import('@/components/ui')['UiFormItem']
    UiIcon: typeof import('@/components/ui')['UiIcon']
    UiInput: typeof import('@/components/ui')['UiInput']
    UiInputGroup: typeof import('@/components/ui')['UiInputGroup']
    UiInputGroupLabel: typeof import('@/components/ui')['UiInputGroupLabel']
    UiInputNumber: typeof import('@/components/ui')['UiInputNumber']
    UiModal: typeof import('@/components/ui')['UiModal']
    UiPagination: typeof import('@/components/ui')['UiPagination']
    UiPopover: typeof import('@/components/ui')['UiPopover']
    UiRadio: typeof import('@/components/ui')['UiRadio']
    UiRadioButton: typeof import('@/components/ui')['UiRadioButton']
    UiRadioGroup: typeof import('@/components/ui')['UiRadioGroup']
    UiSelect: typeof import('@/components/ui')['UiSelect']
    UiSpace: typeof import('@/components/ui')['UiSpace']
    UiSpin: typeof import('@/components/ui')['UiSpin']
    UiSwitch: typeof import('@/components/ui')['UiSwitch']
    UiTag: typeof import('@/components/ui')['UiTag']
    UiTooltip: typeof import('@/components/ui')['UiTooltip']
    VerdictTimeline: typeof import('./components/intel/VerdictTimeline.vue')['default']
  }
}
